server:
  port: 8084
  servlet:
    context-path: /bookings

spring:
  application:
    name: booking-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/booking-air-db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:Abc123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: booking-service
    instance-id: ${spring.application.name}:${server.port}

app:
  services:
    flights: http://localhost:8082/flights
    seats: http://localhost:8083/seats